import { IFarmer } from './domain/models/farmer'

export const FarmerMock: IFarmer[] = [
  {
    name: 'João Silva',
    farmName: 'Fazenda Esperança',
    document: '12345678901',
    city: 'Campinas',
    state: 'SP',
    totalArea: 100.0,
    agriculturalArea: 30.0,
    vegetationArea: 20.0,
    plantedCrops: ['corn', 'coffee', 'cotton'],
  },
  {
    name: 'Maria Santos',
    farmName: 'Fazenda Progresso',
    document: '23456789012',
    city: 'Uberlândia',
    state: 'MG',
    totalArea: 150.0,
    agriculturalArea: 40.0,
    vegetationArea: 30.0,
    plantedCrops: ['sugar_cane', 'corn'],
  },
  {
    name: 'Carlos Oliveira',
    farmName: 'Fazenda Aurora',
    document: '34567890123',
    city: 'Belo Horizonte',
    state: 'MG',
    totalArea: 200.0,
    agriculturalArea: 50.0,
    vegetationArea: 40.0,
    plantedCrops: ['coffee'],
  },
  {
    name: 'Ana Rocha',
    farmName: 'Fazenda Harmonia',
    document: '45678901234',
    city: 'Recife',
    state: 'PE',
    totalArea: 250.0,
    agriculturalArea: 60.0,
    vegetationArea: 50.0,
    plantedCrops: ['cotton'],
  },
  {
    name: 'Lucas Pereira',
    farmName: 'Fazenda Sol Nascente',
    document: '56789012345',
    city: 'Brasília',
    state: 'DF',
    totalArea: 180.0,
    agriculturalArea: 40.0,
    vegetationArea: 20.0,
    plantedCrops: ['corn', 'coffee'],
  },
  {
    name: 'Isabela Almeida',
    farmName: 'Fazenda Doce Vida',
    document: '67890123456',
    city: 'Curitiba',
    state: 'PR',
    totalArea: 120.0,
    agriculturalArea: 30.0,
    vegetationArea: 20.0,
    plantedCrops: ['coffee'],
  },
  {
    name: 'Eduardo Costa',
    farmName: 'Fazenda Verdejante',
    document: '78901234567',
    city: 'Fortaleza',
    state: 'CE',
    totalArea: 220.0,
    agriculturalArea: 70.0,
    vegetationArea: 50.0,
    plantedCrops: ['sugar_cane', 'corn', 'coffee'],
  },
  {
    name: 'Camila Lima',
    farmName: 'Fazenda Dourada',
    document: '89012345678',
    city: 'Porto Alegre',
    state: 'RS',
    totalArea: 300.0,
    agriculturalArea: 80.0,
    vegetationArea: 60.0,
    plantedCrops: ['corn', 'cotton'],
  },
  {
    name: 'Gustavo Pereira',
    farmName: 'Fazenda Abundante',
    document: '90123456789',
    city: 'São Paulo',
    state: 'SP',
    totalArea: 180.0,
    agriculturalArea: 50.0,
    vegetationArea: 30.0,
    plantedCrops: ['sugar_cane', 'coffee'],
  },
  {
    name: 'Laura Mendes',
    farmName: 'Fazenda Vista Café',
    document: '12345098765',
    city: 'Salvador',
    state: 'BA',
    totalArea: 250.0,
    agriculturalArea: 60.0,
    vegetationArea: 40.0,
    plantedCrops: ['coffee'],
  },
  {
    name: 'Vinícius Santos',
    farmName: 'Fazenda Algodão Real',
    document: '98765432101',
    city: 'Goiânia',
    state: 'GO',
    totalArea: 120.0,
    agriculturalArea: 40.0,
    vegetationArea: 20.0,
    plantedCrops: ['cotton'],
  },
  {
    name: 'Juliana Costa',
    farmName: 'Fazenda Serenidade',
    document: '87654321012',
    city: 'Manaus',
    state: 'AM',
    totalArea: 180.0,
    agriculturalArea: 50.0,
    vegetationArea: 30.0,
    plantedCrops: ['sugar_cane'],
  },
  {
    name: 'Rafael Oliveira',
    farmName: 'Fazenda Do Café',
    document: '76543210987',
    city: 'Porto Velho',
    state: 'RO',
    totalArea: 200.0,
    agriculturalArea: 60.0,
    vegetationArea: 40.0,
    plantedCrops: ['coffee', 'corn'],
  },
]
